using CalamityMod.Buffs.DamageOverTime;
using CalamityMod.Buffs.StatBuffs;
using CalamityMod.Buffs.StatDebuffs;
using CalamityMod.Dusts;
using CalamityMod.Items;
using CalamityMod.Items.Accessories;
using CalamityMod.Items.Armor.Plaguebringer;
using CalamityMod.Items.Armor.SnowRuffian;
using CalamityMod.Items.DraedonMisc;
using CalamityMod.Items.Fishing.BrimstoneCragCatches;
using CalamityMod.Items.Fishing.SunkenSeaCatches;
using CalamityMod.Items.LoreItems;
using CalamityMod.Items.Materials;
using CalamityMod.Items.Placeables;
using CalamityMod.Items.SummonItems;
using CalamityMod.Items.TreasureBags.MiscGrabBags;
using CalamityMod.Items.Weapons.Magic;
using CalamityMod.Items.Weapons.Melee;
using CalamityMod.Items.Weapons.Ranged;
using CalamityMod.Items.Weapons.Rogue;
using CalamityMod.Items.Weapons.Summon;
using CalamityMod.NPCs.AquaticScourge;
using CalamityMod.NPCs.BrimstoneElemental;
using CalamityMod.NPCs.CalClone;
using CalamityMod.NPCs.CeaselessVoid;
using CalamityMod.NPCs.Crabulon;
using CalamityMod.NPCs.Cryogen;
using CalamityMod.NPCs.DesertScourge;
using CalamityMod.NPCs.DevourerofGods;
using CalamityMod.NPCs.ExoMechs;
using CalamityMod.NPCs.ExoMechs.Thanatos;
using CalamityMod.NPCs.HiveMind;
using CalamityMod.NPCs.Leviathan;
using CalamityMod.NPCs.NormalNPCs;
using CalamityMod.NPCs.OldDuke;
using CalamityMod.NPCs.Perforator;
using CalamityMod.NPCs.PlaguebringerGoliath;
using CalamityMod.NPCs.Polterghast;
using CalamityMod.NPCs.Providence;
using CalamityMod.NPCs.Ravager;
using CalamityMod.NPCs.SlimeGod;
using CalamityMod.NPCs.SupremeCalamitas;
using CalamityMod.NPCs.TownNPCs;
using CalamityMod.NPCs.Yharon;
using CalamityMod.Projectiles.Boss;
using CalamityMod.Projectiles.Healing;
using CalamityMod.Projectiles.Melee;
using CalamityMod.Projectiles.Ranged;
using CalamityMod.Projectiles.Rogue;
using CalamityMod.Projectiles.Summon;
using CalamityMod.Projectiles.Typeless;
using CalamityMod.Tiles.Furniture.CraftingStations;
using Terraria.ModLoader;

namespace CalamityOverhaul
{
    /// <summary>
    /// 所有用于引用外部模组内部内容的ID集中地
    /// </summary>
    internal class CWRID : ICWRLoader
    {
        public static int Item_Heresy => ModContent.ItemType<Heresy>();
        public static int Item_BurntSienna => ModContent.ItemType<BurntSienna>();
        public static int Item_DubiousPlating => ModContent.ItemType<DubiousPlating>();
        public static int Item_Rock => ModContent.ItemType<Rock>();
        public static int Item_BloodOrb => ModContent.ItemType<BloodOrb>();
        public static int Item_Terminus => ModContent.ItemType<Terminus>();
        public static int Item_LoreAwakening => ModContent.ItemType<LoreAwakening>();
        public static int Item_SquirrelSquireStaff => ModContent.ItemType<SquirrelSquireStaff>();
        public static int Item_ThrowingBrick => ModContent.ItemType<ThrowingBrick>();
        public static int Item_Brimlish => ModContent.ItemType<Brimlish>();
        public static int Item_WaveSkipper => ModContent.ItemType<WaveSkipper>();
        public static int Item_ExoPrism => ModContent.ItemType<ExoPrism>();
        public static int Item_DraedonsForge => ModContent.ItemType<CalamityMod.Items.Placeables.Furniture.CraftingStations.DraedonsForge>();
        public static int Item_RogueEmblem => ModContent.ItemType<RogueEmblem>();
        public static int Item_SnowRuffianMask => ModContent.ItemType<SnowRuffianMask>();
        public static int Item_SnowRuffianChestplate => ModContent.ItemType<SnowRuffianChestplate>();
        public static int Item_SnowRuffianGreaves => ModContent.ItemType<SnowRuffianGreaves>();
        public static int Item_PurifiedGel => ModContent.ItemType<PurifiedGel>();
        public static int Item_VulcaniteLance => ModContent.ItemType<VulcaniteLance>();
        public static int Item_Brimlance => ModContent.ItemType<Brimlance>();
        public static int Item_ContinentalGreatbow => ModContent.ItemType<ContinentalGreatbow>();
        public static int Item_BrimstoneFury => ModContent.ItemType<BrimstoneFury>();
        public static int Item_Helstorm => ModContent.ItemType<Helstorm>();
        public static int Item_Hellborn => ModContent.ItemType<Hellborn>();
        public static int Item_AuricBar => ModContent.ItemType<AuricBar>();
        public static int Item_GrandGuardian => ModContent.ItemType<GrandGuardian>();
        public static int Item_SomaPrime => ModContent.ItemType<SomaPrime>();
        public static int Item_Infinity => ModContent.ItemType<Infinity>();
        public static int Item_PlagueKeeper => ModContent.ItemType<PlagueKeeper>();
        public static int Item_Hellkite => ModContent.ItemType<Hellkite>();
        public static int Item_Contagion => ModContent.ItemType<Contagion>();
        public static int Item_PlagueCellCanister => ModContent.ItemType<PlagueCellCanister>();
        public static int Item_PlaguebringerCarapace => ModContent.ItemType<PlaguebringerCarapace>();
        public static int Item_InfectedArmorPlating => ModContent.ItemType<InfectedArmorPlating>();
        public static int Item_PlaguebringerVisor => ModContent.ItemType<PlaguebringerVisor>();
        public static int Item_PlaguebringerPistons => ModContent.ItemType<PlaguebringerPistons>();
        public static int Item_Lazhar => ModContent.ItemType<Lazhar>();
        public static int Item_ScoriaBar => ModContent.ItemType<ScoriaBar>();
        public static int Item_BloodSample => ModContent.ItemType<BloodSample>();
        public static int Item_BlightedGel => ModContent.ItemType<BlightedGel>();
        public static int Item_RottenMatter => ModContent.ItemType<RottenMatter>();
        public static int Item_MidasPrime => ModContent.ItemType<MidasPrime>();
        public static int Item_CrackshotColt => ModContent.ItemType<CrackshotColt>();
        public static int Item_HolyCollider => ModContent.ItemType<HolyCollider>();
        public static int Item_CelestialClaymore => ModContent.ItemType<CelestialClaymore>();
        public static int Item_DivineGeode => ModContent.ItemType<DivineGeode>();
        public static int Item_StormlionMandible => ModContent.ItemType<StormlionMandible>();
        public static int Item_DiseasedPike => ModContent.ItemType<DiseasedPike>();
        public static int Item_HellionFlowerSpear => ModContent.ItemType<HellionFlowerSpear>();
        public static int Item_Pandemic => ModContent.ItemType<Pandemic>();
        public static int Item_SulphurousGrabber => ModContent.ItemType<SulphurousGrabber>();
        public static int Item_TheSyringe => ModContent.ItemType<TheSyringe>();
        public static int Item_PestilentDefiler => ModContent.ItemType<PestilentDefiler>();
        public static int Item_TheHive => ModContent.ItemType<TheHive>();
        public static int Item_BlightSpewer => ModContent.ItemType<BlightSpewer>();
        public static int Item_Malevolence => ModContent.ItemType<Malevolence>();
        public static int Item_PlagueStaff => ModContent.ItemType<PlagueStaff>();
        public static int Item_SparklingEmpress => ModContent.ItemType<SparklingEmpress>();
        public static int Item_SeaPrism => ModContent.ItemType<SeaPrism>();
        public static int Item_PearlShard => ModContent.ItemType<PearlShard>();
        public static int Item_DragoonDrizzlefish => ModContent.ItemType<DragoonDrizzlefish>();
        public static int Item_Murasama => ModContent.ItemType<Murasama>();
        public static int Item_PlasmaDriveCore => ModContent.ItemType<PlasmaDriveCore>();
        public static int Item_MysteriousCircuitry => ModContent.ItemType<MysteriousCircuitry>();
        public static int Item_EncryptedSchematicHell => ModContent.ItemType<EncryptedSchematicHell>();
        public static int Item_LuxorsGift => ModContent.ItemType<LuxorsGift>();
        public static int Item_EternalBlizzard => ModContent.ItemType<EternalBlizzard>();
        public static int Item_Arbalest => ModContent.ItemType<Arbalest>();
        public static int Item_AshesofCalamity => ModContent.ItemType<AshesofCalamity>();
        public static int Item_CoreofEleum => ModContent.ItemType<CoreofEleum>();
        public static int Item_Condemnation => ModContent.ItemType<Condemnation>();
        public static int Item_AshesofAnnihilation => ModContent.ItemType<AshesofAnnihilation>();
        public static int Item_Vehemence => ModContent.ItemType<Vehemence>();
        public static int Item_ValkyrieRay => ModContent.ItemType<ValkyrieRay>();
        public static int Item_Violence => ModContent.ItemType<Violence>();
        public static int Item_Vigilance => ModContent.ItemType<Vigilance>();
        public static int Item_DeathstareRod => ModContent.ItemType<DeathstareRod>();
        public static int Item_ArmoredShell => ModContent.ItemType<ArmoredShell>();
        public static int Item_DarkPlasma => ModContent.ItemType<DarkPlasma>();
        public static int Item_TwistingNether => ModContent.ItemType<TwistingNether>();
        public static int Item_Excelsus => ModContent.ItemType<Excelsus>();
        public static int Item_TheObliterator => ModContent.ItemType<TheObliterator>();
        public static int Item_Deathwind => ModContent.ItemType<Deathwind>();
        public static int Item_DeathhailStaff => ModContent.ItemType<DeathhailStaff>();
        public static int Item_StaffoftheMechworm => ModContent.ItemType<StaffoftheMechworm>();
        public static int Item_Eradicator => ModContent.ItemType<Eradicator>();
        public static int Item_StarterBag => ModContent.ItemType<StarterBag>();
        public static int Item_CosmicDischarge => ModContent.ItemType<CosmicDischarge>();
        public static int Item_Norfleet => ModContent.ItemType<Norfleet>();
        public static int Item_CosmiliteBar => ModContent.ItemType<CosmiliteBar>();
        public static int NPC_Cataclysm => ModContent.NPCType<Cataclysm>();
        public static int NPC_SepulcherHead => ModContent.NPCType<SepulcherHead>();
        public static int NPC_SepulcherBody => ModContent.NPCType<SepulcherBody>();
        public static int NPC_SepulcherTail => ModContent.NPCType<SepulcherTail>();
        public static int NPC_Yharon => ModContent.NPCType<Yharon>();
        public static int NPC_SlimeGodCore => ModContent.NPCType<SlimeGodCore>();
        public static int NPC_Providence => ModContent.NPCType<Providence>();
        public static int NPC_PlaguebringerGoliath => ModContent.NPCType<PlaguebringerGoliath>();
        public static int NPC_PerforatorHive => ModContent.NPCType<PerforatorHive>();
        public static int NPC_Anahita => ModContent.NPCType<Anahita>();
        public static int NPC_Leviathan => ModContent.NPCType<Leviathan>();
        public static int NPC_HiveMind => ModContent.NPCType<HiveMind>();
        public static int NPC_DevourerofGodsHead => ModContent.NPCType<DevourerofGodsHead>();
        public static int NPC_DevourerofGodsBody => ModContent.NPCType<DevourerofGodsBody>();
        public static int NPC_DevourerofGodsTail => ModContent.NPCType<DevourerofGodsTail>();
        public static int NPC_Cryogen => ModContent.NPCType<Cryogen>();
        public static int NPC_Crabulon => ModContent.NPCType<Crabulon>();
        public static int NPC_BrimstoneElemental => ModContent.NPCType<BrimstoneElemental>();
        public static int NPC_KingSlimeJewelRuby => ModContent.NPCType<KingSlimeJewelRuby>();
        public static int NPC_KingSlimeJewelSapphire => ModContent.NPCType<KingSlimeJewelSapphire>();
        public static int NPC_EbonianPaladin => ModContent.NPCType<EbonianPaladin>();
        public static int NPC_CrimulanPaladin => ModContent.NPCType<CrimulanPaladin>();
        public static int NPC_SplitEbonianPaladin => ModContent.NPCType<SplitEbonianPaladin>();
        public static int NPC_SplitCrimulanPaladin => ModContent.NPCType<SplitCrimulanPaladin>();
        public static int NPC_Catastrophe => ModContent.NPCType<Catastrophe>();
        public static int NPC_Draedon => ModContent.NPCType<Draedon>();
        public static int NPC_RavagerHead2 => ModContent.NPCType<RavagerHead2>();
        public static int NPC_DarkEnergy => ModContent.NPCType<DarkEnergy>();
        public static int NPC_PolterghastHook => ModContent.NPCType<PolterghastHook>();
        public static int NPC_CalamitasClone => ModContent.NPCType<CalamitasClone>();
        public static int NPC_AquaticScourgeBodyAlt => ModContent.NPCType<AquaticScourgeBodyAlt>();
        public static int NPC_SupremeCalamitas => ModContent.NPCType<SupremeCalamitas>();
        public static int NPC_ThanatosHead => ModContent.NPCType<ThanatosHead>();
        public static int NPC_THIEF => ModContent.NPCType<THIEF>();
        public static int NPC_WITCH => ModContent.NPCType<WITCH>();
        public static int NPC_SEAHOE => ModContent.NPCType<SEAHOE>();
        public static int NPC_DILF => ModContent.NPCType<DILF>();//什么叫他妈的DILF？？？？
        public static int NPC_DesertScourgeHead => ModContent.NPCType<DesertScourgeHead>();
        public static int NPC_AquaticScourgeHead => ModContent.NPCType<AquaticScourgeHead>();
        public static int NPC_OldDuke => ModContent.NPCType<OldDuke>();
        public static int Proj_CatastropheClaymoreSparkle => ModContent.ProjectileType<CatastropheClaymoreSparkle>();
        public static int Proj_AngelicBeam => ModContent.ProjectileType<AngelicBeam>();
        public static int Proj_AstralRound => ModContent.ProjectileType<AstralRound>();
        public static int Proj_AstrealArrow => ModContent.ProjectileType<AstrealArrow>();
        public static int Proj_AuralisBullet => ModContent.ProjectileType<AuralisBullet>();
        public static int Proj_CosmicIceBurst => ModContent.ProjectileType<CosmicIceBurst>();
        public static int Proj_BarinadeArrow => ModContent.ProjectileType<BarinadeArrow>();
        public static int Proj_BoltArrow => ModContent.ProjectileType<BoltArrow>();
        public static int Proj_Nuke => ModContent.ProjectileType<Nuke>();
        public static int Proj_AegisFlame => ModContent.ProjectileType<AegisFlame>();
        public static int Proj_DarkMasterBeam => ModContent.ProjectileType<DarkMasterBeam>();
        public static int Proj_DarkMasterClone => ModContent.ProjectileType<DarkMasterClone>();
        public static int Proj_OverlyDramaticDukeSummoner => ModContent.ProjectileType<OverlyDramaticDukeSummoner>();
        public static int Proj_MythrilFlare => ModContent.ProjectileType<MythrilFlare>();
        public static int Proj_Brimlash2 => ModContent.ProjectileType<Brimlash2>();
        public static int Proj_BrimlashProj => ModContent.ProjectileType<BrimlashProj>();
        public static int Proj_BalefulHarvesterProjectile => ModContent.ProjectileType<BalefulHarvesterProjectile>();
        public static int Proj_WaveSkipperProjectile => ModContent.ProjectileType<WaveSkipperProjectile>();
        public static int Proj_DeathsAscensionProjectile => ModContent.ProjectileType<DeathsAscensionProjectile>();
        public static int Proj_DarklightGreatswordSlashCreator => ModContent.ProjectileType<DarklightGreatswordSlashCreator>();
        public static int Proj_DarkBeam => ModContent.ProjectileType<DarkBeam>();
        public static int Proj_CometQuasherMeteor => ModContent.ProjectileType<CometQuasherMeteor>();
        public static int Proj_DesertScourgeSpit => ModContent.ProjectileType<DesertScourgeSpit>();
        public static int Proj_Razorwind => ModContent.ProjectileType<Razorwind>();
        public static int Proj_Brimblast => ModContent.ProjectileType<Brimblast>();
        public static int Proj_IceBombFriendly => ModContent.ProjectileType<IceBombFriendly>();
        public static int Proj_AtaraxiaBoom => ModContent.ProjectileType<AtaraxiaBoom>();
        public static int Proj_AtaraxiaMain => ModContent.ProjectileType<AtaraxiaMain>();
        public static int Proj_AtaraxiaSide => ModContent.ProjectileType<AtaraxiaSide>();
        public static int Proj_BrimstoneBoom => ModContent.ProjectileType<BrimstoneBoom>();
        public static int Proj_AftershockRock => ModContent.ProjectileType<AftershockRock>();
        public static int Proj_UniversalGenesisStar => ModContent.ProjectileType<UniversalGenesisStar>();
        public static int Proj_UniversalGenesisStarcaller => ModContent.ProjectileType<UniversalGenesisStarcaller>();
        public static int Proj_UltimaBolt => ModContent.ProjectileType<UltimaBolt>();
        public static int Proj_UltimaRay => ModContent.ProjectileType<UltimaRay>();
        public static int Proj_UltimaSpark => ModContent.ProjectileType<UltimaSpark>();
        public static int Proj_Bolt => ModContent.ProjectileType<Bolt>();
        public static int Proj_TelluricGlareArrow => ModContent.ProjectileType<TelluricGlareArrow>();
        public static int Proj_SulphuricBlast => ModContent.ProjectileType<SulphuricBlast>();
        public static int Proj_StormSurgeTornado => ModContent.ProjectileType<StormSurgeTornado>();
        public static int Proj_SputterCometBig => ModContent.ProjectileType<SputterCometBig>();
        public static int Proj_PlasmaBlast => ModContent.ProjectileType<PlasmaBlast>();
        public static int Proj_AstralStar => ModContent.ProjectileType<AstralStar>();
        public static int Proj_SpykerProj => ModContent.ProjectileType<SpykerProj>();
        public static int Proj_LostSoulFriendly => ModContent.ProjectileType<LostSoulFriendly>();
        public static int Proj_Shroom => ModContent.ProjectileType<Shroom>();
        public static int Proj_SeasSearingBubble => ModContent.ProjectileType<SeasSearingBubble>();
        public static int Proj_SeasSearingSecondary => ModContent.ProjectileType<SeasSearingSecondary>();
        public static int Proj_ArcherfishShot => ModContent.ProjectileType<ArcherfishShot>();
        public static int Proj_FishronRPG => ModContent.ProjectileType<FishronRPG>();
        public static int Proj_ImpactRound => ModContent.ProjectileType<ImpactRound>();
        public static int Proj_PristineSecondary => ModContent.ProjectileType<PristineSecondary>();
        public static int Proj_PristineFire => ModContent.ProjectileType<PristineFire>();
        public static int Proj_PlanarRipperBolt => ModContent.ProjectileType<PlanarRipperBolt>();
        public static int Proj_PlagueTaintedDrone => ModContent.ProjectileType<PlagueTaintedDrone>();
        public static int Proj_PlagueTaintedProjectile => ModContent.ProjectileType<PlagueTaintedProjectile>();
        public static int Proj_ShockblastRound => ModContent.ProjectileType<ShockblastRound>();
        public static int Proj_P90Round => ModContent.ProjectileType<P90Round>();
        public static int Proj_EmesisGore => ModContent.ProjectileType<EmesisGore>();
        public static int Proj_FlakKrakenProjectile => ModContent.ProjectileType<FlakKrakenProjectile>();
        public static int Proj_FlakToxicannonProjectile => ModContent.ProjectileType<FlakToxicannonProjectile>();
        public static int Proj_FeatherLarge => ModContent.ProjectileType<FeatherLarge>();
        public static int Proj_SlimeStream => ModContent.ProjectileType<SlimeStream>();
        public static int Proj_ChargedBlast => ModContent.ProjectileType<ChargedBlast>();
        public static int Proj_AuricBullet => ModContent.ProjectileType<AuricBullet>();
        public static int Proj_AquaBlast => ModContent.ProjectileType<AquaBlast>();
        public static int Proj_AquaBlastToxic => ModContent.ProjectileType<AquaBlastToxic>();
        public static int Proj_PlagueArrow => ModContent.ProjectileType<PlagueArrow>();
        public static int Proj_NitroShot => ModContent.ProjectileType<NitroShot>();
        public static int Proj_MarksmanShot => ModContent.ProjectileType<MarksmanShot>();
        public static int Proj_RicoshotCoin => ModContent.ProjectileType<RicoshotCoin>();
        public static int Proj_MineralMortarProjectile => ModContent.ProjectileType<MineralMortarProjectile>();
        public static int Proj_MiniSharkron => ModContent.ProjectileType<MiniSharkron>();
        public static int Proj_TyphoonArrow => ModContent.ProjectileType<TyphoonArrow>();
        public static int Proj_IcicleArrowProj => ModContent.ProjectileType<IcicleArrowProj>();
        public static int Proj_DrataliornusFlame => ModContent.ProjectileType<DrataliornusFlame>();
        public static int Proj_VanquisherArrowProj => ModContent.ProjectileType<VanquisherArrowProj>();
        public static int Proj_DaemonsFlameArrow => ModContent.ProjectileType<DaemonsFlameArrow>();
        public static int Proj_VernalBolt => ModContent.ProjectileType<VernalBolt>();
        public static int Proj_CorrodedShell => ModContent.ProjectileType<CorrodedShell>();
        public static int Proj_RealmRavagerBullet => ModContent.ProjectileType<RealmRavagerBullet>();
        public static int Proj_CorinthPrimeAirburstGrenade => ModContent.ProjectileType<CorinthPrimeAirburstGrenade>();
        public static int Proj_SmallCoral => ModContent.ProjectileType<SmallCoral>();
        public static int Proj_LeafArrow => ModContent.ProjectileType<LeafArrow>();
        public static int Proj_BrimstoneBolt => ModContent.ProjectileType<BrimstoneBolt>();
        public static int Proj_ClamorRifleProj => ModContent.ProjectileType<ClamorRifleProj>();
        public static int Proj_ClaretCannonProj => ModContent.ProjectileType<ClaretCannonProj>();
        public static int Proj_CondemnationArrowHoming => ModContent.ProjectileType<CondemnationArrowHoming>();
        public static int Proj_FlurrystormIceChunk => ModContent.ProjectileType<FlurrystormIceChunk>();
        public static int Proj_SquirrelSquireAcorn => ModContent.ProjectileType<SquirrelSquireAcorn>();
        public static int Proj_DracoBeam => ModContent.ProjectileType<DracoBeam>();
        public static int Proj_EarthProj => ModContent.ProjectileType<EarthProj>();
        public static int Proj_FossilShard => ModContent.ProjectileType<FossilShard>();
        public static int Proj_GalacticaComet => ModContent.ProjectileType<GalacticaComet>();
        public static int Proj_ThornBase => ModContent.ProjectileType<ThornBase>();
        public static int Proj_Flarefrost => ModContent.ProjectileType<Flarefrost>();
        public static int Proj_FloodtideShark => ModContent.ProjectileType<FloodtideShark>();
        public static int Proj_GreenWater => ModContent.ProjectileType<GreenWater>();
        public static int Proj_DarkBall => ModContent.ProjectileType<DarkBall>();
        public static int Proj_VolcanicFireball => ModContent.ProjectileType<VolcanicFireball>();
        public static int Proj_VolcanicFireballLarge => ModContent.ProjectileType<VolcanicFireballLarge>();
        public static int Proj_TerratomereSwordBeam => ModContent.ProjectileType<TerratomereSwordBeam>();
        public static int Proj_ExcelsusMain => ModContent.ProjectileType<ExcelsusMain>();
        public static int Proj_ExcelsusBlue => ModContent.ProjectileType<ExcelsusBlue>();
        public static int Proj_ExcelsusPink => ModContent.ProjectileType<ExcelsusPink>();
        public static int Proj_MirrorBlast => ModContent.ProjectileType<MirrorBlast>();
        public static int Proj_StormRulerProj => ModContent.ProjectileType<StormRulerProj>();
        public static int Proj_StarnightBeam => ModContent.ProjectileType<StarnightBeam>();
        public static int Proj_PrismaticWave => ModContent.ProjectileType<PrismaticWave>();
        public static int Proj_RSSolarFlare => ModContent.ProjectileType<RSSolarFlare>();
        public static int Proj_ReaverHealOrb => ModContent.ProjectileType<ReaverHealOrb>();
        public static int Proj_BloodBall => ModContent.ProjectileType<BloodBall>();
        public static int Proj_GhastlySoulLarge => ModContent.ProjectileType<GhastlySoulLarge>();
        public static int Proj_GhastlySoulMedium => ModContent.ProjectileType<GhastlySoulMedium>();
        public static int Proj_GhastlySoulSmall => ModContent.ProjectileType<GhastlySoulSmall>();
        public static int Proj_UltimusCleaverDust => ModContent.ProjectileType<UltimusCleaverDust>();
        public static int Proj_CausticEdgeProjectile => ModContent.ProjectileType<CausticEdgeProjectile>();
        public static int Proj_PrismaticBeam => ModContent.ProjectileType<PrismaticBeam>();
        public static int Proj_TerratomereSlashCreator => ModContent.ProjectileType<TerratomereSlashCreator>();
        public static int Proj_Voidragon => ModContent.ProjectileType<CalamityMod.Projectiles.Ranged.Voidragon>();
        public static int Proj_TorrentialArrow => ModContent.ProjectileType<TorrentialArrow>();
        public static int Proj_HallowPointRoundProj => ModContent.ProjectileType<HallowPointRoundProj>();
        public static int Proj_Aquashard => ModContent.ProjectileType<Aquashard>();
        public static int Proj_ArcherfishRing => ModContent.ProjectileType<ArcherfishRing>();
        public static int Proj_CardHeart => ModContent.ProjectileType<CardHeart>();
        public static int Proj_CardSpade => ModContent.ProjectileType<CardSpade>();
        public static int Proj_CardDiamond => ModContent.ProjectileType<CardDiamond>();
        public static int Proj_CardClub => ModContent.ProjectileType<CardClub>();
        public static int Tile_PlagueInfuser => ModContent.TileType<PlagueInfuser>();
        public static int Tile_DraedonsForge => ModContent.TileType<DraedonsForge>();
        public static int Tile_SCalAltar => ModContent.TileType<SCalAltar>();
        public static int Tile_SCalAltarLarge => ModContent.TileType<SCalAltarLarge>();
        public static int Tile_SulphurousSand => ModContent.TileType<CalamityMod.Tiles.Abyss.SulphurousSand>();
        public static int Tile_SulphurousSandstone => ModContent.TileType<CalamityMod.Tiles.Abyss.SulphurousSandstone>();
        public static int Buff_Plague => ModContent.BuffType<Plague>();
        public static int Buff_ElementalMix => ModContent.BuffType<ElementalMix>();
        public static int Buff_VulnerabilityHex => ModContent.BuffType<VulnerabilityHex>();
        public static int Buff_MarkedforDeath => ModContent.BuffType<MarkedforDeath>();
        public static int Buff_BrutalCarnage => ModContent.BuffType<BrutalCarnage>();
        public static int Buff_ArmorCrunch => ModContent.BuffType<ArmorCrunch>();
        public static int Buff_GodSlayerInferno => ModContent.BuffType<GodSlayerInferno>();
        public static int Buff_Shadowflame => ModContent.BuffType<Shadowflame>();
        public static int Buff_HolyFlames => ModContent.BuffType<HolyFlames>();
        public static int Buff_BrainRot => ModContent.BuffType<BrainRot>();
        public static int Buff_Nightwither => ModContent.BuffType<Nightwither>();
        public static int Buff_BurningBlood => ModContent.BuffType<BurningBlood>();
        public static int Buff_TemporalSadness => ModContent.BuffType<TemporalSadness>();
        public static int Buff_GlacialState => ModContent.BuffType<GlacialState>();
        public static int Buff_AstralInfectionDebuff => ModContent.BuffType<AstralInfectionDebuff>();
        public static int Buff_BrimstoneFlames => ModContent.BuffType<BrimstoneFlames>();
        public static int Dust_AstralOrange => ModContent.DustType<AstralOrange>();
        public static int Dust_AstralBlue => ModContent.DustType<AstralBlue>();
        public static int Dust_Brimstone => 235;//是的，灾厄拿夺命杖的粒子当硫磺火焰粒子用
        public static int ItemGroup_RogueWeapon => 570;//是的，570是盗贼武器物品组ID
        //用于加载数据
        void ICWRLoader.SetupData() {
            
        }
    }
}
