using Microsoft.Xna.Framework.Graphics;
using ReLogic.Content;

namespace CalamityOverhaul.Common
{
    /// <summary>全局着色器资源装载点</summary>
    [VaultLoaden(CWRConstant.Effects)]
    public static class EffectLoader
    {
        public static Asset<Effect> Blackwall { get; set; }
        public static Asset<Effect> PowerSFShader { get; set; }
        public static Asset<Effect> EowAcid { get; set; }
        public static Asset<Effect> EowGeyser { get; set; }
        public static Asset<Effect> SkeletronCurseVeil { get; set; }
        public static Asset<Effect> SkeletronGhostArm { get; set; }
        public static Asset<Effect> SkeletronSpinStorm { get; set; }
        public static Asset<Effect> SkeletronCurseFlame { get; set; }
        public static Asset<Effect> SkeletronBoneMatter { get; set; }
        public static Asset<Effect> SkeletronSpecterRibbon { get; set; }
        public static Asset<Effect> GolemSunTelegraph { get; set; }
        public static Asset<Effect> GolemMagmaVein { get; set; }
        public static Asset<Effect> GolemSolarFlare { get; set; }
        public static Asset<Effect> GolemTrapWork { get; set; }
        public static Asset<Effect> GolemThruster { get; set; }
        public static Asset<Effect> CultistSigil { get; set; }
        public static Asset<Effect> CultistElementOrb { get; set; }
        public static Asset<Effect> CultistVeil { get; set; }
        public static Asset<Effect> CultistCrystal { get; set; }
        public static Asset<Effect> FishronStormSky { get; set; }
        public static Asset<Effect> FishronTornado { get; set; }
        public static Asset<Effect> FishronTsunami { get; set; }
        public static Asset<Effect> FishronTelegraph { get; set; }
        public static Asset<Effect> FishronGrabVeil { get; set; }
        public static Asset<Effect> EmpressLanceBeam { get; set; }
        public static Asset<Effect> EmpressSunbeam { get; set; }
        public static Asset<Effect> EmpressAurora { get; set; }
        public static Asset<Effect> EmpressScreenPrism { get; set; }
        public static Asset<Effect> QueenPrismBeam { get; set; }
        public static Asset<Effect> QueenPrismCrystal { get; set; }
        public static Asset<Effect> QueenGaleField { get; set; }
        public static Asset<Effect> BrainHeartbeatPulse { get; set; }
        public static Asset<Effect> BrainMirrorImage { get; set; }
        public static Asset<Effect> BrainRift { get; set; }
        public static Asset<Effect> EocBloodFog { get; set; }
        public static Asset<Effect> EocBloodTrail { get; set; }
        public static Asset<Effect> EocTelegraph { get; set; }
        public static Asset<Effect> DeerBlizzardVeil { get; set; }
        public static Asset<Effect> DeerFrostFissure { get; set; }
        public static Asset<Effect> MLordDeathray { get; set; }
        public static Asset<Effect> MLordEclipseSky { get; set; }
        public static Asset<Effect> MLordCelestial { get; set; }
        public static Asset<Effect> QueenSwarmFlow { get; set; }
        public static Asset<Effect> QueenHoneyPool { get; set; }
        public static Asset<Effect> QueenBeeTelegraph { get; set; }
        public static Asset<Effect> PlanteraVine { get; set; }
        public static Asset<Effect> PlanteraSporeFog { get; set; }
        public static Asset<Effect> PlanteraBloom { get; set; }
        public static Asset<Effect> WofFleshWall { get; set; }
        public static Asset<Effect> WofMawVortex { get; set; }
        public static Asset<Effect> WofRetinaBeam { get; set; }
        public static Asset<Effect> WofBloodCurtain { get; set; }
        public static Asset<Effect> WofBloodSea { get; set; }
        public static Asset<Effect> BKSGelSurge { get; set; }
        public static Asset<Effect> BKSGelPool { get; set; }
        public static Asset<Effect> WarpShader { get; set; }
        public static Asset<Effect> NeutronPulsar { get; set; }
        public static Asset<Effect> NeutronPulseBeam { get; set; }
        public static Asset<Effect> NeutronWarp { get; set; }
        public static Asset<Effect> PrimeHalo { get; set; }
        public static Asset<Effect> PrimeTelegraph { get; set; }
        public static Asset<Effect> PrimeSkullBeam { get; set; }
        public static Asset<Effect> PrimeArcChain { get; set; }
        public static Asset<Effect> PrimeChargeVortex { get; set; }
        public static Asset<Effect> PrimeShockRing { get; set; }
        public static Asset<Effect> PrimeImpactFrame { get; set; }
        public static Asset<Effect> PrimeHeatWake { get; set; }
        public static Asset<Effect> PrimeAfterimage { get; set; }
        public static Asset<Effect> DestroyerThermalOutline { get; set; }
        public static Asset<Effect> DestroyerSlash { get; set; }
        public static Asset<Effect> DestroyerBeam { get; set; }
        public static Asset<Effect> DestroyerHeatWake { get; set; }
        public static Asset<Effect> DestroyerTelegraph { get; set; }
        public static Asset<Effect> TwinsEyeOverlay { get; set; }
        public static Asset<Effect> TwinsDeathRayBeam { get; set; }
        public static Asset<Effect> TwinsChargeVortex { get; set; }
        public static Asset<Effect> MechSky { get; set; }
        public static Asset<Effect> SulfurSeaSky { get; set; }
        public static Asset<Effect> TzeentchSky { get; set; }
        public static Asset<Effect> GradientTrail { get; set; }
        public static Asset<Effect> DeductDraw { get; set; }
        public static Asset<Effect> AccretionDisk { get; set; }
        public static Asset<Effect> AriaBlackHole { get; set; }
        public static Asset<Effect> AriaGammaRay { get; set; }
        public static Asset<Effect> AriaStarRing { get; set; }
        public static Asset<Effect> CommandersBeam { get; set; }
        public static Asset<Effect> DropPodFlame { get; set; }
        public static Asset<Effect> DropPodShockwave { get; set; }
        public static Asset<Effect> DropPodHeatHaze { get; set; }
        public static Asset<Effect> CyberShockwave { get; set; }
        public static Asset<Effect> CyberRestartField { get; set; }
        public static Asset<Effect> CyberBoundaryRing { get; set; }
        public static Asset<Effect> CyberGlitchBolt { get; set; }
        public static Asset<Effect> CyberRiftSlash { get; set; }
        public static Asset<Effect> CyberReform { get; set; }
        public static Asset<Effect> CyberTraceBeam { get; set; }
        public static Asset<Effect> CyberEnergyOrb { get; set; }
        public static Asset<Effect> CyberDetonation { get; set; }
        public static Asset<Effect> CyberDataArc { get; set; }
        public static Asset<Effect> CyberspaceField { get; set; }
        public static Asset<Effect> CyberDomainSky { get; set; }
        public static Asset<Effect> CyberPanel { get; set; }
        public static Asset<Effect> CyberDomainPanel { get; set; }
        public static Asset<Effect> SHPCModPanel { get; set; }
        public static Asset<Effect> SHPCModMossVine { get; set; }
        public static Asset<Effect> SHPCModCoralFlow { get; set; }
        public static Asset<Effect> CyberpunkItemFilter { get; set; }
        public static Asset<Effect> HotwindPanel { get; set; }
        public static Asset<Effect> DraedonPanel { get; set; }
        public static Asset<Effect> ForestPanel { get; set; }
        public static Asset<Effect> QuestChronicleBg { get; set; }
        public static Asset<Effect> NotifBadge { get; set; }
        public static Asset<Effect> ShepelGlitch { get; set; }
        public static Asset<Effect> SeaDomainField { get; set; }
        public static Asset<Effect> OceanCurrentTrail { get; set; }
        public static Asset<Effect> OceanWaterBlob { get; set; }
        public static Asset<Effect> HalibutPanel { get; set; }
        public static Asset<Effect> HalibutAtlasBg { get; set; }
        public static Asset<Effect> OniGhostScroll { get; set; }
        public static Asset<Effect> OniGhostShadow { get; set; }
        public static Asset<Effect> WraithScapeArm { get; set; }
        public static Asset<Effect> WraithRevivalHud { get; set; }
        public static Asset<Effect> GhostHandSheath { get; set; }
        public static Asset<Effect> HeadlessShadeBody { get; set; }
        public static Asset<Effect> HeadlessShadeCut { get; set; }
        public static Asset<Effect> WraithLantern { get; set; }
        public static Asset<Effect> BrideCurtain { get; set; }
        public static Asset<Effect> GhostRain { get; set; }
        public static Asset<Effect> OniPaperBurn { get; set; }
        public static Asset<Effect> OniVigorInk { get; set; }
        public static Asset<Effect> OniStanceBlade { get; set; }
        public static Asset<Effect> OniMeiStand { get; set; }
        public static Asset<Effect> OniInkWipe { get; set; }
        public static Asset<Effect> OniMoon { get; set; }
        public static Asset<Effect> HalibutHudEye { get; set; }
        public static Asset<Effect> HalibutHudGauge { get; set; }
        public static Asset<Effect> EncyclopediaKnowledge { get; set; }
        public static Asset<Effect> ElysiumHalo { get; set; }
        public static Asset<Effect> ElysiumStaff { get; set; }
        public static Asset<Effect> SerpentTrail { get; set; }
        public static Asset<Effect> CelestialStar { get; set; }
        public static Asset<Effect> BrimstoneDomain { get; set; }
        public static Asset<Effect> BrimstoneBlastWave { get; set; }
        public static Asset<Effect> KingSlimeRoyalAura { get; set; }
        public static Asset<Effect> KingSlimeShockwave { get; set; }
        public static Asset<Effect> KingSlimeRoyalBeam { get; set; }
        public static Asset<Effect> BKSNinjaSlash { get; set; }
        public static Asset<Effect> BKSCrownFX { get; set; }
        public static Asset<Effect> KingSlimeBloodWing { get; set; }
        public static Asset<Effect> CosmicCrescent { get; set; }
        public static Asset<Effect> WitchBrimstoneDomain { get; set; }
        public static Asset<Effect> CelestialDomain { get; set; }
        public static Asset<Effect> ProverbsGhostDomain { get; set; }
        public static Asset<Effect> RevelationPlague { get; set; }
        public static Asset<Effect> VoidPortal { get; set; }
        public static Asset<Effect> AbandonedPortalPanel { get; set; }
        public static Asset<Effect> VoidSuction { get; set; }
        public static Asset<Effect> VoidArrival { get; set; }
        public static Asset<Effect> CyberBossBar { get; set; }
        public static Asset<Effect> HackRamArc { get; set; }
        public static Asset<Effect> HackDeckPanel { get; set; }
        public static Asset<Effect> SHPCCoreOrb { get; set; }
        public static Asset<Effect> CyberwareRadialPanel { get; set; }
        public static Asset<Effect> CyberwarePanel { get; set; }
        public static Asset<Effect> CyberwareBulletTime { get; set; }
        public static Asset<Effect> VictorEyelidTransition { get; set; }
        public static Asset<Effect> VictorCyberPortal { get; set; }
        public static Asset<Effect> TBUGCorruptRift { get; set; }
        public static Asset<Effect> TBUGTerminalPanel { get; set; }
        public static Asset<Effect> IndustrialTerminal { get; set; }
        public static Asset<Effect> ThermalPanel { get; set; }
        public static Asset<Effect> ThermalBar { get; set; }
        public static Asset<Effect> ThermalBatteryCore { get; set; }
        public static Asset<Effect> TeslaGuardRing { get; set; }
        public static Asset<Effect> UEPipelineFlow { get; set; }
        public static Asset<Effect> CreativePipelineFlow { get; set; }
        public static Asset<Effect> ThermalHeatHaze { get; set; }
        public static Asset<Effect> VoidColonySky { get; set; }
        public static Asset<Effect> VoidFog { get; set; }
        public static Asset<Effect> VoidTimeShift { get; set; }
        public static Asset<Effect> GlitchHead { get; set; }
        public static Asset<Effect> ArchitectureWarp { get; set; }
        public static Asset<Effect> VoidLaserCannon { get; set; }
        public static Asset<Effect> SignalTowerLightning { get; set; }
        public static Asset<Effect> SignalTowerElectrified { get; set; }
        public static Asset<Effect> SignalTowerVirusBroadcast { get; set; }
        public static Asset<Effect> SignalTowerHoverOutline { get; set; }
        public static Asset<Effect> DecryptionPanelBackground { get; set; }
        public static Asset<Effect> BreachMatrixAxisHighlight { get; set; }
        public static Asset<Effect> GatlinTracer { get; set; }
        public static Asset<Effect> GatlinImpactBurst { get; set; }
        public static Asset<Effect> HyperionExhaust { get; set; }
        public static Asset<Effect> HyperionBlast { get; set; }
        public static Asset<Effect> BrimstoneDialogueBox { get; set; }
        public static Asset<Effect> SeaDialogueBox { get; set; }
        public static Asset<Effect> OniNarrativePanel { get; set; }
        public static Asset<Effect> SulfseaPanel { get; set; }
        public static Asset<Effect> TzeentchPanel { get; set; }
        public static Asset<Effect> EntrustGuideCard { get; set; }
        public static Asset<Effect> CybCourseSky { get; set; }
        public static Asset<Effect> CybCourseLoading { get; set; }
        public static Asset<Effect> CybCourseBoot { get; set; }
        public static Asset<Effect> CybCourseEntryReveal { get; set; }
        public static Asset<Effect> VoidColonyLoading { get; set; }
        public static Asset<Effect> SHPCVoltArc { get; set; }
        public static Asset<Effect> SHPCPlasmaSun { get; set; }
        public static Asset<Effect> SHPCSonicBoom { get; set; }
        public static Asset<Effect> SHPCJudgmentRay { get; set; }
        public static Asset<Effect> SHPCHoloLattice { get; set; }
        public static Asset<Effect> SHPCModThermal { get; set; }
        public static Asset<Effect> SHPCModSniperLock { get; set; }
        public static Asset<Effect> SHPCModHeavyMaul { get; set; }
        public static Asset<Effect> SHPCModHexCell { get; set; }
        public static Asset<Effect> SHPCModExtenderCleave { get; set; }
        public static Asset<Effect> SHPCModErgoEcho { get; set; }
        public static Asset<Effect> SHPCModShardburst { get; set; }
        public static Asset<Effect> SHPCModCapacitorBank { get; set; }
        public static Asset<Effect> SHPCModBrace { get; set; }
        public static Asset<Effect> ArcaneRift { get; set; }
        public static Asset<Effect> ArcaneHighDimension { get; set; }
        public static Asset<Effect> ArcaneRealityTremor { get; set; }
        public static Asset<Effect> WeaverSlashTrail { get; set; }
        public static Asset<Effect> WeaverWraith { get; set; }
        public static Asset<Effect> WeaverSoulVortex { get; set; }
        public static Asset<Effect> WeaverMaterialize { get; set; }
        public static Asset<Effect> EnergySlashTrail { get; set; }
        public static Asset<Effect> RebelSlashTrail { get; set; }
        public static Asset<Effect> StormSlashTrail { get; set; }
        public static Asset<Effect> DragonSlashTrail { get; set; }
        public static Asset<Effect> DawnshatterSlash { get; set; }
        public static Asset<Effect> DragonSoulSerpent { get; set; }
        public static Asset<Effect> DragonSporeBeam { get; set; }
        public static Asset<Effect> BarrenPulse { get; set; }
        public static Asset<Effect> NeutronGravityWell { get; set; }
        public static Asset<Effect> GlacierSpike { get; set; }
        public static Asset<Effect> FrostAurora { get; set; }
        public static Asset<Effect> FrostJudgment { get; set; }
        public static Asset<Effect> DivineSourceBladeGlow { get; set; }
        public static Asset<Effect> DivineSourceArc { get; set; }
        public static Asset<Effect> DivineSourceCrescent { get; set; }
        public static Asset<Effect> DivineSourceImpact { get; set; }
        public static Asset<Effect> OniWorldGrade { get; set; }
        public static Asset<Effect> KikasaGrade { get; set; }
        public static Asset<Effect> KikasaSky { get; set; }
        public static Asset<Effect> KikasaFlip { get; set; }
        public static Asset<Effect> KikasaItemForm { get; set; }
        public static Asset<Effect> KikasaThrallForm { get; set; }
        public static Asset<Effect> KikasaVaultPanel { get; set; }
        public static Asset<Effect> KikasaScene { get; set; }
        public static Asset<Effect> KikasaHand { get; set; }
        public static Asset<Effect> KikasaNarrativePanel { get; set; }
        public static Asset<Effect> KikasaMoonRay { get; set; }
        public static Asset<Effect> KikasaEaterRift { get; set; }
        public static Asset<Effect> KikasaDeerclopsFrost { get; set; }
        public static Asset<Effect> KikasaInkDrop { get; set; }
        public static Asset<Effect> KikasaInkSplat { get; set; }
        public static Asset<Effect> KikasaUmbrella { get; set; }
        public static Asset<Effect> KikasaHound { get; set; }
        public static Asset<Effect> KikasaDream { get; set; }
        public static Asset<Effect> KikasaDreamSky { get; set; }
        public static Asset<Effect> KikasaReset { get; set; }
        public static Asset<Effect> OniOmokage { get; set; }
        public static Asset<Effect> OniPaperPeel { get; set; }
        public static Asset<Effect> OniSky { get; set; }
        public static Asset<Effect> OniDomainDeco { get; set; }
        public static Asset<Effect> HimayoPortraitAssembly { get; set; }
        public static Asset<Effect> HimayoPanorama { get; set; }
        public static Asset<Effect> ToriiDissolve { get; set; }
        public static Asset<Effect> OniEye { get; set; }
        public static Asset<Effect> AckBackdrop { get; set; }
        public static Asset<Effect> AckFinale { get; set; }
        public static Asset<Effect> AckGlow { get; set; }
        public static Asset<Effect> OniCrimsonSlash { get; set; }
        public static Asset<Effect> OniCrimsonImpactPost { get; set; }
        public static Asset<Effect> OniCrimsonBloom { get; set; }
        public static Asset<Effect> OniGateRift { get; set; }
        public static Asset<Effect> OniFinaleBlade { get; set; }
        public static Asset<Effect> OniFinalePost { get; set; }
        public static Asset<Effect> OniFinaleWound { get; set; }
        public static Asset<Effect> OniKamuiFlow { get; set; }
        public static Asset<Effect> OniSakuraFlow { get; set; }
        public static Asset<Effect> OniDismember { get; set; }
        public static Asset<Effect> OniAnnihilateArc { get; set; }
        public static Asset<Effect> OniInkThread { get; set; }
        public static Asset<Effect> OniRaikiri { get; set; }
        public static Asset<Effect> OniBellWave { get; set; }
        public static Asset<Effect> OniPuddleMirror { get; set; }
        public static Asset<Effect> OniRainWorld { get; set; }
        public static Asset<Effect> OniRainSky { get; set; }
        public static Asset<Effect> OniRainDescent { get; set; }
        public static Asset<Effect> OniSewage { get; set; }
        public static Asset<Effect> OniSandGarden { get; set; }
        public static Asset<Effect> OniSenjuArm { get; set; }
        public static Asset<Effect> OniPaperMirror { get; set; }
        public static Asset<Effect> SHPCModStormField { get; set; }
        public static Asset<Effect> SHPCModStormBolt { get; set; }
        public static Asset<Effect> SHPCModRecycleCell { get; set; }
        public static Asset<Effect> SHPCModResonanceWave { get; set; }
        public static Asset<Effect> SHPCModResonanceRing { get; set; }
        public static Asset<Effect> SHPCModRedline { get; set; }
        public static Asset<Effect> SHPCModVolatile { get; set; }
        public static Asset<Effect> SHPCModSteadyVolt { get; set; }
        public static Asset<Effect> SHPCModFrostfern { get; set; }
        public static Asset<Effect> SHPCModMagma { get; set; }
        public static Asset<Effect> GraniteArc { get; set; }
        public static Asset<Effect> MarbleSlash { get; set; }
        public static Asset<Effect> BloodAltarRite { get; set; }
        public static Asset<Effect> UnsungheroChess { get; set; }
        public static Asset<Effect> ScrapForm { get; set; }
        public static Asset<Effect> ScrapBeamLine { get; set; }
        public static Asset<Effect> ScrapHeavyBeam { get; set; }
        public static Asset<Effect> ScrapMagnetField { get; set; }
        public static Asset<Effect> ScrapSiegeFilter { get; set; }
        public static Asset<Effect> ShockRing { get; set; }
        public static Asset<Effect> DungeonworldLoading { get; set; }
        public static Asset<Effect> DungeonworldEntryReveal { get; set; }
        public static Asset<Effect> DungeonworldSky { get; set; }
        public static Asset<Effect> DungeonworldFog { get; set; }
    }
}
